In [ ]:
# compare all classification model
# Logistic Regression
# Decision Tree - 86%
# Random Forest
# SVM
# KNN
# Naive Bayes Theorem
# Ensemble techniques - bagging and boosting 
# K-Fold method - applicable for all

In [1]:
# Case Study - 
import os
os.chdir("C:\\Users\\Kumar Sundram\\Desktop\\my data\\DSP27\\Python\\DT")

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
dataset = pd.read_csv("Social_Network_Ads.csv")
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  11021175    Male   42           121315          0
1  17782313    Male   53            67214          0
2  14603818  Female   59           111005          0
3  18188198  Female   39            53414          0
4  19357305    Male   39           114285          0

In [4]:
x = dataset.iloc[:,2:4].values

In [5]:
y = dataset.iloc[:,4].values

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x= sc.fit_transform(x)

C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [7]:
x

array([[ 0.17951354,  0.76103154],
       [ 1.11315372, -1.14804259],
       [ 1.622412  ,  0.39722026],
       [-0.0751156 , -1.63500628],
       [-0.0751156 ,  0.51296235],
       [-0.0751156 ,  0.27205647],
       [-1.68776681, -0.49988685],
       [ 1.622412  ,  1.71449234],
       [ 0.68877182, -0.67642883],
       [ 0.17951354,  0.51010409],
       [-0.66925025, -0.42211381],
       [ 0.7736482 ,  0.48681452],
       [ 1.28290648, -0.40397617],
       [ 1.1980301 ,  1.66971285],
       [ 1.45265924,  1.40703476],
       [ 0.09463716,  1.23391563],
       [ 0.94340096,  0.58523059],
       [ 1.28290648, -0.95915007],
       [ 0.3492663 ,  0.82945347],
       [ 0.60389544,  0.48695567],
       [ 1.02827734, -0.72004384],
       [-1.68776681,  0.2258655 ],
       [ 0.00976078, -1.41410826],
       [ 1.02827734, -0.82625839],
       [-1.00875577,  0.67023751],
       [-1.51801405,  0.21697311],
       [-1.26338491,  0.53166458],
       [-0.15999198, -0.50532108],
       [ 1.45265924,

In [19]:
# Splitting the data into training and testing

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

# Classification Model 1 - Logistic Regression

In [20]:
# Classification Model 1 - Logistic Regression
from sklearn.linear_model import LogisticRegression
logitReg = LogisticRegression()
logitReg.fit(x_train, y_train)

C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [21]:
y_pred = logitReg.predict(x_test)

In [22]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[64,  0],
       [36,  0]], dtype=int64)

In [23]:
# k-fold with logistic regression
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=logitReg, X = x_train, y=y_train, cv=20)
accuracies

C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs

array([0.625     , 0.625     , 0.625     , 0.625     , 0.6875    ,
       0.625     , 0.625     , 0.66666667, 0.66666667, 0.66666667,
       0.66666667, 0.66666667, 0.66666667, 0.64285714, 0.64285714,
       0.64285714, 0.64285714, 0.64285714, 0.64285714, 0.64285714])

In [ ]:
# compare all classification model
# Logistic Regression - 68.75 % 
# Decision Tree - 
# Random Forest
# SVM
# KNN
# Naive Bayes Theorem
# Ensemble techniques - bagging and boosting 
# K-Fold method - applicable for all

# Classification Model 2 - Decision Tree

In [24]:
from sklearn.tree import DecisionTreeClassifier
classifier_dt = DecisionTreeClassifier(criterion = 'entropy')
classifier_dt.fit(x_train, y_train)


DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [25]:
y_pred1 = classifier_dt.predict(x_test)

In [26]:
confusion_matrix(y_test, y_pred1)

array([[48, 16],
       [24, 12]], dtype=int64)

In [27]:
# k-fold with decision tree
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier_dt, X = x_train, y=y_train, cv=20)
accuracies

array([0.75      , 0.5       , 0.4375    , 0.5       , 0.625     ,
       0.5       , 0.5625    , 0.26666667, 0.53333333, 0.73333333,
       0.46666667, 0.46666667, 0.53333333, 0.57142857, 0.64285714,
       0.35714286, 0.64285714, 0.57142857, 0.57142857, 0.5       ])

In [ ]:
# compare all classification model
# Logistic Regression - 68.75 % 
# Decision Tree - 75 %
# Random Forest
# SVM
# KNN
# Naive Bayes Theorem
# Ensemble techniques - bagging and boosting 
# K-Fold method - applicable for all

In [28]:
from sklearn.tree import DecisionTreeClassifier
classifier_dt = DecisionTreeClassifier(criterion = 'gini')
classifier_dt.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [29]:
y_pred1 = classifier_dt.predict(x_test)

In [30]:
confusion_matrix(y_test, y_pred1)

array([[45, 19],
       [23, 13]], dtype=int64)

In [31]:
# k-fold with decision tree
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier_dt, X = x_train, y=y_train, cv=20)
accuracies

array([0.625     , 0.4375    , 0.5       , 0.5625    , 0.5625    ,
       0.625     , 0.5       , 0.2       , 0.53333333, 0.8       ,
       0.6       , 0.6       , 0.66666667, 0.64285714, 0.71428571,
       0.42857143, 0.71428571, 0.64285714, 0.71428571, 0.5       ])

In [ ]:
# compare all classification model
# Logistic Regression - 68.75 % 
# Decision Tree - 80%
    # entropy = 75 %
    # gini - 80%
# Random Forest
# SVM
# KNN
# Naive Bayes Theorem
# Ensemble techniques - bagging and boosting 
# K-Fold method - applicable for all

# Classification Model 3 - Random Forest

In [32]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')
classifier_rf.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [33]:
y_pred2 = classifier_rf.predict(x_test)

In [34]:
confusion_matrix(y_test, y_pred2)

array([[52, 12],
       [28,  8]], dtype=int64)

In [35]:
# k-fold with random forest
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier_rf, X = x_train, y=y_train, cv=20)
accuracies

array([0.625     , 0.5       , 0.375     , 0.5       , 0.5625    ,
       0.625     , 0.6875    , 0.66666667, 0.53333333, 0.8       ,
       0.6       , 0.6       , 0.53333333, 0.71428571, 0.71428571,
       0.5       , 0.57142857, 0.71428571, 0.5       , 0.35714286])

In [ ]:
# compare all classification model
# Logistic Regression - 68.75 % 
# Decision Tree - 80%
    # entropy = 75 %
    # gini - 80%
# Random Forest - 80%
# SVM
# KNN
# Naive Bayes Theorem
# Ensemble techniques - bagging and boosting 
# PCA - Principal Componant analysis - 
# K-Fold method - applicable for all

In [45]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(n_estimators = 10000, criterion = 'gini')
classifier_rf.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10000, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [46]:
y_pred2 = classifier_rf.predict(x_test)

In [47]:
confusion_matrix(y_test, y_pred2)

array([[53, 11],
       [29,  7]], dtype=int64)

In [48]:
# k-fold with random forest
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier_rf, X = x_train, y=y_train, cv=20)
accuracies

KeyboardInterrupt: 

In [ ]:
# compare all classification model
# Logistic Regression - 68.75 % 
# Decision Tree - 80%
    # entropy = 75 %
    # gini - 80%
# Random Forest - 80%
    # tree = 500 - 92.8% 
# SVM
# KNN
# Naive Bayes Theorem
# Ensemble techniques - bagging and boosting 
# PCA - Principal Componant analysis - 
# K-Fold method - applicable for all

# Classification Model 4 - Support Vetor Machine (kernel = Sigmoid)

In [51]:
from sklearn.svm import SVC
classifier_svm_sigmoid = SVC(kernel='sigmoid')
classifier_svm_sigmoid.fit(x_train, y_train)

C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [52]:
y_pred3=classifier_svm_sigmoid.predict(x_test)

In [57]:
confusion_matrix(y_test, y_pred3)

array([[64,  0],
       [36,  0]], dtype=int64)

In [58]:
# k-fold with random forest
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier_svm_sigmoid, X = x_train, y=y_train, cv=20)
accuracies

C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\skle

array([0.625     , 0.625     , 0.625     , 0.625     , 0.3125    ,
       0.625     , 0.625     , 0.66666667, 0.66666667, 0.66666667,
       0.66666667, 0.66666667, 0.66666667, 0.64285714, 0.64285714,
       0.64285714, 0.64285714, 0.64285714, 0.64285714, 0.5       ])

In [ ]:
# compare all classification model
# Logistic Regression - 68.75 % 
# Decision Tree - 80%
    # entropy = 75 %
    # gini - 80%
# Random Forest - 80%
    # tree = 500 - 92.8% 
# SVM -
    # sigmoid - 66.6%
    # rbf - 
# KNN
# Naive Bayes Theorem
# Ensemble techniques - bagging and boosting 
# PCA - Principal Componant analysis - 
# K-Fold method - applicable for all

In [55]:
from sklearn.svm import SVC
classifier_svm_sigmoid = SVC(kernel='rbf')
classifier_svm_sigmoid.fit(x_train, y_train)

C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [56]:
y_pred3=classifier_svm_sigmoid.predict(x_test)

In [59]:
confusion_matrix(y_test, y_pred3)

array([[64,  0],
       [36,  0]], dtype=int64)

In [60]:
# k-fold with SVM
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier_svm_sigmoid, X = x_train, y=y_train, cv=20)
accuracies

C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\skle

array([0.625     , 0.625     , 0.625     , 0.625     , 0.3125    ,
       0.625     , 0.625     , 0.66666667, 0.66666667, 0.66666667,
       0.66666667, 0.66666667, 0.66666667, 0.64285714, 0.64285714,
       0.64285714, 0.64285714, 0.64285714, 0.64285714, 0.5       ])

In [ ]:
# compare all classification model
# Logistic Regression - 68.75 % 
# Decision Tree - 80%
    # entropy = 75 %
    # gini - 80%
# Random Forest - 80%
    # tree = 500 - 92.8% 
# SVM -
    # sigmoid - 66.6%
    # rbf - 66.6%
# KNN
# Naive Bayes Theorem
# Ensemble techniques - bagging and boosting 
# PCA - Principal Componant analysis - 
# K-Fold method - applicable for all

# Classification Model 5 - K Nearest Neighbour (KNN Model)

In [74]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors = 7, metric = 'minkowski', p=2)
classifier_knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=7, p=2,
           weights='uniform')

In [75]:
y_pred4 = classifier_knn.predict(x_test)

In [76]:
confusion_matrix(y_test, y_pred4)

array([[55,  9],
       [32,  4]], dtype=int64)

In [77]:
# k-fold with KNN
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier_knn, X = x_train, y=y_train, cv=20)
accuracies

array([0.5625    , 0.5       , 0.5625    , 0.5625    , 0.4375    ,
       0.625     , 0.625     , 0.66666667, 0.66666667, 0.66666667,
       0.6       , 0.53333333, 0.73333333, 0.64285714, 0.71428571,
       0.5       , 0.64285714, 0.71428571, 0.64285714, 0.21428571])

In [ ]:
# compare all classification model
# Logistic Regression - 68.75 % 
# Decision Tree - 80%
    # entropy = 75 %
    # gini - 80%
# Random Forest - 80%
    # tree = 500 - 92.8% 
# SVM -
    # sigmoid - 66.6%
    # rbf - 66.6%
# KNN - 73.3 %
# Naive Bayes Theorem - adhoc project
# Ensemble techniques - 
    # bagging  
    # boosting 
# PCA - Principal Componant analysis - 
# K-Fold method - applicable for all

# Classification Model 6 - Naive Bayes Theorem

In [78]:
from sklearn.naive_bayes import GaussianNB
classifier_nvt = GaussianNB()
classifier_nvt.fit(x_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [79]:
y_pred5 = classifier_nvt.predict(x_test)

In [80]:
confusion_matrix(y_test, y_pred5)

array([[64,  0],
       [34,  2]], dtype=int64)

In [81]:
# k-fold with Naive Bayes Theorem
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier_nvt, X = x_train, y=y_train, cv=20)
accuracies

array([0.625     , 0.625     , 0.625     , 0.625     , 0.625     ,
       0.625     , 0.625     , 0.66666667, 0.66666667, 0.66666667,
       0.66666667, 0.6       , 0.66666667, 0.64285714, 0.64285714,
       0.64285714, 0.64285714, 0.64285714, 0.64285714, 0.64285714])

In [ ]:
# compare all classification model
# Logistic Regression - 68.75 % 
# Decision Tree - 80%
    # entropy = 75 %
    # gini - 80%
# Random Forest - 80%
    # tree = 500 - 92.8% 
# SVM -
    # sigmoid - 66.6%
    # rbf - 66.6%
# KNN - 73.3 %
# Naive Bayes Theorem - adhoc project - 66.6 %
# Ensemble techniques - 
    # bagging  
    # boosting 
# PCA - Principal Componant analysis - 
# K-Fold method - applicable for all

# Bagging_Classifier_Model-7

In [84]:
from sklearn.ensemble import BaggingClassifier
classifier_bagging = BaggingClassifier(n_estimators=500, max_samples=1.0)
classifier_bagging.fit(x_train, y_train)

BaggingClassifier(base_estimator=None, bootstrap=True,
         bootstrap_features=False, max_features=1.0, max_samples=1.0,
         n_estimators=500, n_jobs=None, oob_score=False, random_state=None,
         verbose=0, warm_start=False)

In [85]:
y_pred6 = classifier_bagging.predict(x_test)

In [86]:
confusion_matrix(y_test, y_pred6)

array([[54, 10],
       [27,  9]], dtype=int64)

In [87]:
# k-fold with Bagging method
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier_bagging, X = x_train, y=y_train, cv=20)
accuracies

array([0.5625    , 0.375     , 0.5       , 0.5625    , 0.5       ,
       0.625     , 0.6875    , 0.4       , 0.6       , 0.66666667,
       0.66666667, 0.66666667, 0.86666667, 0.78571429, 0.64285714,
       0.42857143, 0.64285714, 0.64285714, 0.57142857, 0.5       ])

In [ ]:
# compare all classification model
# Logistic Regression - 68.75 % 
# Decision Tree - 80%
    # entropy = 75 %
    # gini - 80%
# Random Forest - 80%
    # tree = 500 - 92.8% 
# SVM -
    # sigmoid - 66.6%
    # rbf - 66.6%
# KNN - 73.3 %
# Naive Bayes Theorem - adhoc project - 66.6 %
# Ensemble techniques - 
    # bagging - 86.6%
    # boosting 
# PCA - Principal Componant analysis - 
# K-Fold method - applicable for all

# XGBoost_Classifier_Model-8 

In [89]:
from xgboost import XGBClassifier
classifier_xgb = XGBClassifier()
classifier_xgb.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, learning_rate=0.1,
       max_delta_step=0, max_depth=3, min_child_weight=1, missing=None,
       n_estimators=100, n_jobs=1, nthread=None,
       objective='binary:logistic', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
       subsample=1, verbosity=1)

In [90]:
y_pred7 = classifier_xgb.predict(x_test)

In [91]:
confusion_matrix(y_test, y_pred7)

array([[59,  5],
       [29,  7]], dtype=int64)

In [92]:
# k-fold with XGBoost method
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier_xgb, X = x_train, y=y_train, cv=20)
accuracies

array([0.625     , 0.4375    , 0.5625    , 0.5       , 0.3125    ,
       0.625     , 0.75      , 0.53333333, 0.6       , 0.73333333,
       0.6       , 0.6       , 0.8       , 0.71428571, 0.71428571,
       0.42857143, 0.71428571, 0.57142857, 0.64285714, 0.42857143])

In [ ]:
# compare all classification model
# Logistic Regression - 68.75 % 
# Decision Tree - 80%
    # entropy = 75 %
    # gini - 80%
# Random Forest - 80%
    # tree = 500 - 92.8% 
# SVM -
    # sigmoid - 66.6%
    # rbf - 66.6%
# KNN - 73.3 %
# Naive Bayes Theorem - adhoc project - 66.6 %
# Ensemble techniques - 
    # bagging - 86.6%
    # boosting - 80 %
# PCA - Principal Componant analysis - 
# K-Fold method - applicable for all

# Kernel PCA (Principal Component Analysis) - Model 9

In [95]:
from sklearn.decomposition import KernelPCA
classifier_pca = KernelPCA(n_components = 2, kernel ='rbf')
x_train = classifier_pca.fit_transform(x_train)
x_test = classifier_pca.transform(x_test)


In [96]:
# Classification Model 1 - Logistic Regression
from sklearn.linear_model import LogisticRegression
logitReg = LogisticRegression(random_state=0)
logitReg.fit(x_train, y_train)

C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [97]:
y_pred8 = logitReg.predict(x_test)

In [98]:
confusion_matrix(y_test, y_pred8)

array([[64,  0],
       [36,  0]], dtype=int64)

In [99]:
# k-fold with PCA-Logistic
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=logitReg, X = x_train, y=y_train, cv=20)
accuracies

C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Kumar Sundram\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs

array([0.625     , 0.625     , 0.625     , 0.625     , 0.625     ,
       0.625     , 0.625     , 0.66666667, 0.66666667, 0.66666667,
       0.66666667, 0.66666667, 0.66666667, 0.64285714, 0.64285714,
       0.64285714, 0.64285714, 0.64285714, 0.64285714, 0.64285714])

In [ ]:
# compare all classification model
# Logistic Regression - 68.75 % 
# Decision Tree - 80%
    # entropy = 75 %
    # gini - 80%
# Random Forest - 80%
    # tree = 500 - 92.8% 
# SVM -
    # sigmoid - 66.6%
    # rbf - 66.6%
# KNN - 73.3 %
# Naive Bayes Theorem - adhoc project - 66.6 %
# Ensemble techniques - 
    # bagging - 86.6%
    # boosting - 80 %
# PCA - Principal Componant analysis with Logit Regression-  66.6%
# K-Fold method - applicable for all

# Final Validation 
## Random Forest - 92.8%
### bagging - 86.6%
#### boosting - 80 %
##### Decision Tree - 80%
###### KNN - 73.3 %
___________________________________________________________________

####### Logistic Regression - 68.75 % 
######## PCA - Principal Componant analysis with Logit Regression-  66.6%
######## Naive Bayes Theorem - adhoc project - 66.6 %
######## SVM - 66.6 %